name: Publish to Github Pages
on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}

    steps:
      - name: Set runner
        id: set-runner
        run: |
          curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runners"
          runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runners")
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" and .labels[] .name == "self-hosted")')
          if [ -n "$available" ]; then
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "runner-label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-runner
    runs-on: ${{ needs.check-runner.outputs.runner-label }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Live-Image
        run: |
          mkdir -p target/img
          if ! convert -version 2>/dev/null 1>&2; then 
            sudo apt-get install imagemagick
          fi
          convert -size 300x200 -fill '#ffffff' -background '#00000099' -gravity center label:"Last Update:\n$(date +'%d.%m.%Y\n%H:%M') (UTC)" target/img/live-image.png

      - name: Copy files
        run: |
          mkdir -p target/cards/live-image
          cp cards/live-image/live-image.js target/cards/live-image/live-image.js
          echo "<!DOCTYPE html><style>html { background: #666; }</style><p>Hi :)</p><img src='img/live-image.png' />" > target/index.html

      - name: Upload Github Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: target/

      - name: Publish to Github Pages
        uses: actions/deploy-pages@v4.0.0
